import { useSelector } from "react-redux";
export const useLanguage = () => {
  return useSelector((state) => state.languages.language);
};
export const languages = {
  pt: {
    textLogin: "Entrar",
    labelUsername: "Usuário",
    labelPwd: "Senha",
    textTrustThisDevice: "Confiar neste dispositivo",
    textLoginButtonGoogle: "Entrar com Google",
    textDontHaveAccount: "Ainda não é cadastrado?",
    createAccountButton: "Cadastrar agora.",
    textOrLogin: "Ou",
    labelConfirmPwd: "Repita a senha",
    alredyHaveAccText: "Já possui conta?",
    loginButton: "Fazer Login",
    textRegister: "Registrar",
    labelLanguage: "Idioma",
    loading: "Carregando...",
    links: "Rotas",
    textPublic: "Público",
    textPrivate: "Privado",
    textGoTo: "Ir para",
    textPage: "página",
    textSignOut: "Sair",
    textGoToAdm: "Ir para página de administrador",
    textGoToEditor: "Ir para edição",
    textGoToLounge: "Ir para saguão",
    textEditor: "Editor",
    textLounge: "Saguão",
    textAdmin: "Administrador",
    textHomePage: "Página Inicial",
    goHome: "Ir para Página Inicial",
    adminsPage: "Página de Administrador",
    usersList: "Lista de usuários",
    emptyList: "Sem dados",
    welcome: "Bem vindo",
    back: "Voltar",
    editorPage: "Edição",
    employeesList: "Lista de empregados",
    employee: "Funcionário",
    addEmployee: "+ Funcionário",
    delete: "Excluir",
    enterEmpInfo: "Informe os dados do empregado",
    firstName: "Primeiro nome",
    lastName: "Último nome",
    AddEmployeeTitle: "Adicionar Empregados",
    registerCreated: "Registro criado com sucesso.",
  },
  it: {
    textLogin: "Accedi",
    labelUsername: "Nome utente",
    labelPwd: "Password",
    textTrustThisDevice: "Fidati di questo dispositivo",
    textLoginButtonGoogle: "Accedi con Google",
    textDontHaveAccount: "Non hai ancora un account?",
    createAccountButton: "Crea un account ora.",
    textOrLogin: "O",
    labelConfirmPwd: "Conferma Password",
    alredyHaveAccText: "Hai già un account?",
    loginButton: "Accedi",
    textRegister: "Registrati",
    labelLanguage: "Lingua",
    loading: "Caricamento...",
    links: "Link",
    textPublic: "Pubblico",
    textPrivate: "Privato",
    textGoTo: "Vai a",
    textPage: "pagina",
    textSignOut: "Esci",
    textGoToAdm: "Vai alla pagina dell'amministratore",
    textGoToEditor: "Vai all'editor",
    textGoToLounge: "Vai alla sala d'attesa",
    textEditor: "Editor",
    textLounge: "Sala d'attesa",
    textAdmin: "Amministratore",
    textHomePage: "Pagina principale",
    goHome: "Vai alla pagina principale",
    adminsPage: "Pagina degli amministratori",
    usersList: "Lista utenti",
    emptyList: "Nessun dato",
    welcome: "Benvenuto",
    back: "Indietro",
    editorPage: "Modifica",
    employeesList: "Lista dipendenti",
    employee: "Dipendente",
    addEmployee: "+ Dipendente",
    delete: "Elimina",
    enterEmpInfo: "Inserisci informazioni dipendente",
    firstName: "Nome",
    lastName: "Cognome",
    AddEmployeeTitle: "Aggiungi Dipendenti",
    registerCreated: "Registrazione creata con successo.",
  },

  es: {
    textLogin: "Iniciar sesión",
    labelUsername: "Nombre de usuario",
    labelPwd: "Contraseña",
    textTrustThisDevice: "Confía en este dispositivo",
    textLoginButtonGoogle: "Iniciar sesión con Google",
    textDontHaveAccount: "¿No tienes una cuenta?",
    createAccountButton: "Crear una cuenta ahora.",
    textOrLogin: "O",
    labelConfirmPwd: "Confirmar contraseña",
    alredyHaveAccText: "¿Ya tienes una cuenta?",
    loginButton: "Iniciar sesión",
    textRegister: "Registrarse",
    labelLanguage: "Idioma",
    loading: "Cargando...",
    links: "Enlaces",
    textPublic: "Público",
    textPrivate: "Privado",
    textGoTo: "Ir a",
    textPage: "página",
    textSignOut: "Cerrar sesión",
    textGoToAdm: "Ir a la página de administrador",
    textGoToEditor: "Ir al editor",
    textGoToLounge: "Ir al salón",
    textEditor: "Editor",
    textLounge: "Salón",
    textAdmin: "Administrador",
    textHomePage: "Página de inicio",
    goHome: "Ir a la página de inicio",
    adminsPage: "Página de administradores",
    usersList: "Lista de usuarios",
    emptyList: "Sin datos",
    welcome: "Bienvenido",
    back: "Volver",
    editorPage: "Edición",
    employeesList: "Lista de empleados",
    employee: "Empleado",
    addEmployee: "+ Empleado",
    delete: "Eliminar",
    enterEmpInfo: "Ingrese la información del empleado",
    firstName: "Nombre",
    lastName: "Apellido",
    AddEmployeeTitle: "Agregar Empleados",
    registerCreated: "Registro creado exitosamente.",
  },

  fr: {
    textLogin: "Se connecter",
    labelUsername: "Nom d'utilisateur",
    labelPwd: "Mot de passe",
    textTrustThisDevice: "Faites confiance à cet appareil",
    textLoginButtonGoogle: "Se connecter avec Google",
    textDontHaveAccount: "Vous n'avez pas de compte ?",
    createAccountButton: "Créer un compte maintenant.",
    textOrLogin: "Ou",
    labelConfirmPwd: "Confirmer le mot de passe",
    alredyHaveAccText: "Vous avez déjà un compte ?",
    loginButton: "Se connecter",
    textRegister: "S'inscrire",
    labelLanguage: "Langue",
    loading: "Chargement...",
    links: "Liens",
    textPublic: "Public",
    textPrivate: "Privé",
    textGoTo: "Aller à",
    textPage: "page",
    textSignOut: "Déconnexion",
    textGoToAdm: "Aller à la page d'administration",
    textGoToEditor: "Aller à l'éditeur",
    textGoToLounge: "Aller au salon",
    textEditor: "Éditeur",
    textLounge: "Salon",
    textAdmin: "Administrateur",
    textHomePage: "Page d'accueil",
    goHome: "Aller à la page d'accueil",
    adminsPage: "Page des administrateurs",
    usersList: "Liste des utilisateurs",
    emptyList: "Pas de données",
    welcome: "Bienvenue",
    back: "Retour",
    editorPage: "Édition",
    employeesList: "Liste des employés",
    employee: "Employé",
    addEmployee: "+ Employé",
    delete: "Supprimer",
    enterEmpInfo: "Entrez les informations de l'employé",
    firstName: "Prénom",
    lastName: "Nom de famille",
    AddEmployeeTitle: "Ajouter des Employés",
    registerCreated: "Enregistrement créé avec succès.",
  },
  en: {
    textLogin: "Login",
    labelUsername: "Username",
    labelPwd: "Password",
    textTrustThisDevice: "Trust this device",
    textLoginButtonGoogle: "Login with Google",
    textDontHaveAccount: "Don't have an account yet?",
    createAccountButton: "Create account now.",
    textOrLogin: "Or",
    labelConfirmPwd: "Confirm Password",
    alredyHaveAccText: "Already have an account?",
    loginButton: "Log In",
    textRegister: "Register",
    labelLanguage: "Language",
    loading: "Loading...",
    links: "Links",
    textPublic: "Public",
    textPrivate: "Private",
    textGoTo: "Go to",
    textPage: "page",
    textSignOut: "Sign Out",
    textGoToAdm: "Go to admin page",
    textGoToEditor: "Go to editor",
    textGoToLounge: "Go to lounge",
    textEditor: "Editor",
    textLounge: "Lounge",
    textAdmin: "Admin",
    textHomePage: "Home Page",
    goHome: "Go to Home Page",
    adminsPage: "Admin Page",
    usersList: "Users List",
    emptyList: "No data",
    welcome: "Welcome",
    back: "Back",
    editorPage: "Editing",
    employeesList: "Employees List",
    employee: "Employee",
    addEmployee: "+ Employee",
    delete: "Delete",
    enterEmpInfo: "Enter employee information",
    firstName: "First Name",
    lastName: "Last Name",
    AddEmployeeTitle: "Add Employees",
    registerCreated: "Register created.",
  },
};
